### ISSUE TITLE
Bugs in interp in cpp_funcs.R

### ISSUE THREAD

**Issue by alex1770** [nicholasdavies/newcovid#2]
Two problems with the function interp which occurs five times in cpp_funcs.R:

1. The interpolation is the wrong way round: it should be 
`return (1 - f) * curve[i] + f * curve[i + 1];`
not
`return f * curve[i] + (1 - f) * curve[i + 1];`

2. The test `(x >= (curve.size() - 1) * 0.01)` can fail when `i` would be out of range and access illegal memory because 0.01 doesn't have an exact floating point representation. E.g., `interp(0.0499999999999999958, myarray)` will break if myarray has length 6. The fix is to calculate `i` then test `if (i >= curve.size()-1) return curve.back();` instead.

**Comment by nicholasdavies** [comment]
Thanks Alex, these issues have been fixed.
